version: '3.1'
services:
  odoo:
    image: odoo:17.0
    ports:
      - "1876:8069"
    command: ["--log-level=debug"]
    container_name: "bpp"
    restart: "unless-stopped"
    volumes:
      - ./conf:/etc/odoo
      - ./addons:/mnt/extra-addons
    
    networks:
      - dockernet
    environment:
      - DB_PORT=5432

networks:
  dockernet:
    name: dockernet
    external: true